In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\rafael ortega\appdata\local\programs\python\python37\lib\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\users\rafael ortega\appdata\local\programs\python\python37\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#pd.read_csv('./Datasets EDA/Datos de pacientes.csv')

datos_pacientes = pd.read_excel('./Datasets EDA/Datos de pacientes.xlsx')

c:\Users\Rafael Ortega\AppData\Local\Programs\Python\Python37\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [4]:
datos_pacientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Apellido                        863 non-null    object
 1   Comentarios                     33 non-null     object
 2   Correo electronico              444 non-null    object
 3   Direccion                       492 non-null    object
 4   DNI                             751 non-null    float64
 5   Edad                            698 non-null    object
 6   Fecha de creacion del registro  710 non-null    datetime64[ns]
 7   Fecha Nacimiento                698 non-null    datetime64[ns]
 8   ID Paciente                     895 non-null    int64
 9   Localidad                       718 non-null    object
 10  Nº de Afiliado                  664 non-null    float64
 11  Nombres                         866 non-null    object
 12  Obra Social                     839 non-null    object
 13  Plan Obra Social                247 non-null    object
 14  Telefono Fijo                   45 non-null     object
 15  Telefono Móvil                  642 non-null    object
dtypes: datetime64[ns](2), float64(2), int64(1), object(11)
memory usage: 112.0+ KB

In [5]:
datos_pacientes.head(20)

,Apellido,Comentarios,Correo electronico,Direccion,DNI,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Localidad,Nº de Afiliado,Nombres,Obra Social,Plan Obra Social,Telefono Fijo,Telefono Móvil
0,DePrueba,esposa del dr.,ivanags@hotmail.com,9 de Julio 170 - Planta Alta,27480893.0,43 años,NaT,1979-10-22,1,Rafaela,2.748089e+07,Ivana,IAPOS,NaN,435015,342154073978
1,Zurbriggen,NaN,NaN,Chiaraviglio 198,14338475.0,61 años,NaT,1961-06-16,2,Rafaela,1.433848e+07,María Cristina,OSECAC,NaN,437113,NaN
2,Zoratti,NaN,graciela_ferreteria@hotmail.com,Alvear 946,17008004.0,58 años,NaT,1964-07-24,3,Rafaela,1.700800e+07,Graciela,CENTRO ASISTENCIAL,NaN,NaN,15683213
3,Trossero,NaN,dtrossero@hotmail.com,NaN,29215013.0,NaN,NaT,NaT,4,Ataliva,2.921501e+07,Daniela Laura,CENTRO ASISTENCIAL,NaN,NaN,03493 15405038
4,Ingaramo,NaN,flia.vinderola@hotmail.com,Chacabuco 347,6480084.0,81 años,NaT,1941-06-13,5,Rafaela,6.049401e+17,Alcira,SANCOR,NaN,504349,15612356
5,Condrac,NaN,keilacondrac@hotmail.com,NaN,29054123.0,40 años,NaT,1980-04-24,6,Rafaela,1.554944e+08,Keila,AMUR,NaN,NaN,15655392
6,Roque,NaN,sandraroque@arnet.com.ar,Las Heras 257,22054718.0,47 años,NaT,1971-04-07,7,Rafaela,2.920500e+04,Sandra,OSPAC,NaN,NaN,15646617
7,Pelagagge,NaN,NaN,Jose Marti 358,4100505.0,73 años,NaT,1941-12-13,8,Rafaela,2.704101e+12,Elda,OSPIL,NaN,502358,NaN
8,Pogonza,NaN,NaN,Ramon y Cajal 868,3963708.0,76 años,NaT,1940-10-01,9,Rafaela,1.523795e+08,Anita,AMUR,NaN,421120,NaN
9,Bender,NaN,NaN,NaN,NaN,NaN,NaT,NaT,10,NaN,NaN,Gisela,OSDE,NaN,NaN,NaN
10,Romero,NaN,lilydvromero@hotmail.com,Lincoln 391,17963832.0,50 años,NaT,1966-11-18,11,Rafaela,1.796383e+07,Liliana,CENTRO ASISTENCIAL,NaN,NaN,15586494
11,Bulacio,NaN,NaN,Anduiza 871,14047288.0,53 años,NaT,1960-12-11,12,Rafaela,1.404729e+07,Nelli,IAPOS,NaN,435753,NaN
12,Villarruel,"Debe orden de eco, 1ER AVISO",NaN,NaN,24671759.0,NaN,NaT,NaT,13,Villa Trinidad,NaN,Mariela,SANCOR,NaN,NaN,0349115408004
13,Dellasanta,NaN,pauladellasanta@hotmail.com,Dr. Zavalla 3239,NaN,48 años,NaT,1971-08-02,14,Santa Fe,NaN,Paula,PARTICULAR,NaN,NaN,342 155303165
14,Corró,NaN,paulacorro17@gmail.com,Bv. Lehmann 426,34673666.0,33 años,NaT,1989-06-04,15,Rafaela,2.560001e+07,Paula,AVALIAN,AS200 NG,NaN,15658623
15,Inwilkenried,NaN,NaN,Chile 577,3691443.0,80 años,NaT,1938-01-19,16,Rafaela,NaN,Marta,OSECAC,NaN,506636,NaN
16,Heit,prefiere comunicarse por facebook,heitbrenda6@gmail.com,Av de los Inmigrantes 115,33776486.0,31 años,NaT,1989-08-10,17,Bella Italia,3.377649e+07,Brenda,IAPOS,NaN,424447,15211000
17,Serruya,NaN,lasole22_ar@hotmail.com,Las Camelias 251,31115188.0,35 años,NaT,1984-10-24,18,Rafaela,3.111519e+07,Maria Soledad,IAPOS,NaN,432610,15610946
18,Sosa,Casa de los padres,natisosa_cami@hotmail.com,27 de Septiembre 1555,26058764.0,45 años,NaT,1977-08-31,19,Rafaela,2.605876e+07,Natalia,OSPAT,NaN,NaN,15574515
19,Rostagno,NaN,NaN,Av. Providenti 523,5967731.0,65 años,NaT,1949-06-23,21,Rafaela,1.504429e+11,Onelia Angela,PAMI,NaN,434544,NaN

In [6]:
datos_pacientes.head()

,Apellido,Comentarios,Correo electronico,Direccion,DNI,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Localidad,Nº de Afiliado,Nombres,Obra Social,Plan Obra Social,Telefono Fijo,Telefono Móvil
0,DePrueba,esposa del dr.,ivanags@hotmail.com,9 de Julio 170 - Planta Alta,27480893.0,43 años,NaT,1979-10-22,1,Rafaela,2.748089e+07,Ivana,IAPOS,NaN,435015,342154073978
1,Zurbriggen,NaN,NaN,Chiaraviglio 198,14338475.0,61 años,NaT,1961-06-16,2,Rafaela,1.433848e+07,María Cristina,OSECAC,NaN,437113,NaN
2,Zoratti,NaN,graciela_ferreteria@hotmail.com,Alvear 946,17008004.0,58 años,NaT,1964-07-24,3,Rafaela,1.700800e+07,Graciela,CENTRO ASISTENCIAL,NaN,NaN,15683213
3,Trossero,NaN,dtrossero@hotmail.com,NaN,29215013.0,NaN,NaT,NaT,4,Ataliva,2.921501e+07,Daniela Laura,CENTRO ASISTENCIAL,NaN,NaN,03493 15405038
4,Ingaramo,NaN,flia.vinderola@hotmail.com,Chacabuco 347,6480084.0,81 años,NaT,1941-06-13,5,Rafaela,6.049401e+17,Alcira,SANCOR,NaN,504349,15612356

In [7]:
datos_pacientes.drop(['Nº de Afiliado','Localidad','DNI', 'Telefono Móvil'], axis=1, inplace=True)

In [8]:
datos_pacientes

,Apellido,Comentarios,Correo electronico,Direccion,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Nombres,Obra Social,Plan Obra Social,Telefono Fijo
0,DePrueba,esposa del dr.,ivanags@hotmail.com,9 de Julio 170 - Planta Alta,43 años,NaT,1979-10-22,1,Ivana,IAPOS,NaN,435015
1,Zurbriggen,NaN,NaN,Chiaraviglio 198,61 años,NaT,1961-06-16,2,María Cristina,OSECAC,NaN,437113
2,Zoratti,NaN,graciela_ferreteria@hotmail.com,Alvear 946,58 años,NaT,1964-07-24,3,Graciela,CENTRO ASISTENCIAL,NaN,NaN
3,Trossero,NaN,dtrossero@hotmail.com,NaN,NaN,NaT,NaT,4,Daniela Laura,CENTRO ASISTENCIAL,NaN,NaN
4,Ingaramo,NaN,flia.vinderola@hotmail.com,Chacabuco 347,81 años,NaT,1941-06-13,5,Alcira,SANCOR,NaN,504349
...,...,...,...,...,...,...,...,...,...,...,...,...
890,Stochero,NaN,NaN,NaN,NaN,2023-02-17,NaT,955,Lara,PARTICULAR,NaN,NaN
891,Bertossi,NaN,NaN,NaN,NaN,2023-02-27,NaT,956,María,DASUTEN,NaN,NaN
892,Castellano,NaN,NaN,NaN,NaN,2023-03-02,NaT,957,German,CENTRO ASISTENCIAL,NaN,NaN
893,Gomez,NaN,NaN,NaN,27 años,2023-03-02,1996-02-27,958,Jorgelina,CENTRO ASISTENCIAL,NaN,NaN
894,Eier,NaN,NaN,NaN,NaN,2023-03-02,NaT,959,Gisela,SANCOR,NaN,NaN

In [9]:
datos_pacientes.keys()

Index(['Apellido', 'Comentarios', 'Correo electronico', 'Direccion', 'Edad',
       'Fecha de creacion del registro', 'Fecha Nacimiento', 'ID Paciente',
       'Nombres', 'Obra Social', 'Plan Obra Social', 'Telefono Fijo'],
      dtype='object')

In [10]:
datos_pacientes.reindex(columns=['ID Paciente','Nombres','Apellido', 'Fecha de creacion del registro', 'Fecha Nacimiento', 'Obra Social'])

,ID Paciente,Nombres,Apellido,Fecha de creacion del registro,Fecha Nacimiento,Obra Social
0,1,Ivana,DePrueba,NaT,1979-10-22,IAPOS
1,2,María Cristina,Zurbriggen,NaT,1961-06-16,OSECAC
2,3,Graciela,Zoratti,NaT,1964-07-24,CENTRO ASISTENCIAL
3,4,Daniela Laura,Trossero,NaT,NaT,CENTRO ASISTENCIAL
4,5,Alcira,Ingaramo,NaT,1941-06-13,SANCOR
...,...,...,...,...,...,...
890,955,Lara,Stochero,2023-02-17,NaT,PARTICULAR
891,956,María,Bertossi,2023-02-27,NaT,DASUTEN
892,957,German,Castellano,2023-03-02,NaT,CENTRO ASISTENCIAL
893,958,Jorgelina,Gomez,2023-03-02,1996-02-27,CENTRO ASISTENCIAL
894,959,Gisela,Eier,2023-03-02,NaT,SANCOR

In [11]:
datos_pacientes

,Apellido,Comentarios,Correo electronico,Direccion,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Nombres,Obra Social,Plan Obra Social,Telefono Fijo
0,DePrueba,esposa del dr.,ivanags@hotmail.com,9 de Julio 170 - Planta Alta,43 años,NaT,1979-10-22,1,Ivana,IAPOS,NaN,435015
1,Zurbriggen,NaN,NaN,Chiaraviglio 198,61 años,NaT,1961-06-16,2,María Cristina,OSECAC,NaN,437113
2,Zoratti,NaN,graciela_ferreteria@hotmail.com,Alvear 946,58 años,NaT,1964-07-24,3,Graciela,CENTRO ASISTENCIAL,NaN,NaN
3,Trossero,NaN,dtrossero@hotmail.com,NaN,NaN,NaT,NaT,4,Daniela Laura,CENTRO ASISTENCIAL,NaN,NaN
4,Ingaramo,NaN,flia.vinderola@hotmail.com,Chacabuco 347,81 años,NaT,1941-06-13,5,Alcira,SANCOR,NaN,504349
...,...,...,...,...,...,...,...,...,...,...,...,...
890,Stochero,NaN,NaN,NaN,NaN,2023-02-17,NaT,955,Lara,PARTICULAR,NaN,NaN
891,Bertossi,NaN,NaN,NaN,NaN,2023-02-27,NaT,956,María,DASUTEN,NaN,NaN
892,Castellano,NaN,NaN,NaN,NaN,2023-03-02,NaT,957,German,CENTRO ASISTENCIAL,NaN,NaN
893,Gomez,NaN,NaN,NaN,27 años,2023-03-02,1996-02-27,958,Jorgelina,CENTRO ASISTENCIAL,NaN,NaN
894,Eier,NaN,NaN,NaN,NaN,2023-03-02,NaT,959,Gisela,SANCOR,NaN,NaN

In [12]:
filtered_fecha_creacion = datos_pacientes.dropna(subset=['Fecha de creacion del registro'])
filtered_fecha_nacimiento = filtered_fecha_creacion.dropna(subset=['Fecha Nacimiento'])

In [13]:
filtered_fecha_nacimiento.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 560 entries, 185 to 893
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Apellido                        560 non-null    object
 1   Comentarios                     15 non-null     object
 2   Correo electronico              324 non-null    object
 3   Direccion                       389 non-null    object
 4   Edad                            560 non-null    object
 5   Fecha de creacion del registro  560 non-null    datetime64[ns]
 6   Fecha Nacimiento                560 non-null    datetime64[ns]
 7   ID Paciente                     560 non-null    int64
 8   Nombres                         560 non-null    object
 9   Obra Social                     555 non-null    object
 10  Plan Obra Social                215 non-null    object
 11  Telefono Fijo                   15 non-null     object
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 56.9+ KB

In [14]:
filtered_fecha_nacimiento['Obra Social'].fillna('No obra social', inplace=True)

c:\Users\Rafael Ortega\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [15]:
filtered_fecha_nacimiento.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 560 entries, 185 to 893
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Apellido                        560 non-null    object
 1   Comentarios                     15 non-null     object
 2   Correo electronico              324 non-null    object
 3   Direccion                       389 non-null    object
 4   Edad                            560 non-null    object
 5   Fecha de creacion del registro  560 non-null    datetime64[ns]
 6   Fecha Nacimiento                560 non-null    datetime64[ns]
 7   ID Paciente                     560 non-null    int64
 8   Nombres                         560 non-null    object
 9   Obra Social                     560 non-null    object
 10  Plan Obra Social                215 non-null    object
 11  Telefono Fijo                   15 non-null     object
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 56.9+ KB

In [16]:
filtered_fecha_nacimiento['edad primera cita'] = ((pd.to_datetime(filtered_fecha_nacimiento['Fecha de creacion del registro']) - pd.to_datetime(filtered_fecha_nacimiento['Fecha Nacimiento'])).dt.days / 365.25).astype(int)

C:\Users\Rafael Ortega\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [17]:
filtered_fecha_nacimiento

,Apellido,Comentarios,Correo electronico,Direccion,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Nombres,Obra Social,Plan Obra Social,Telefono Fijo,edad primera cita
185,Gaeta,NaN,gaetanatalia@gmail.com,Sargento Cabral 495,37 años,2015-09-17,1983-01-30,198,Natalia,OSDE,NaN,NaN,32
186,Acosta,NaN,gisela.angeles@hotmail.com,Aconcagua 618,32 años,2015-09-24,1985-05-15,199,Gisela,OSDE,NaN,NaN,30
187,Furlong,NaN,leticiafurlong@live.com.ar,Montes de Oca 445,36 años,2015-10-05,1982-02-02,201,Leticia,IAPOS,NaN,NaN,33
188,Fornero,NaN,mariafornero@gmail.com,Las Araucarias 2130,36 años,2015-10-23,1981-05-20,202,Maria,OSDE,NaN,NaN,34
189,Lelli,NaN,kacomertes@hotmail.com,Uruguat 545,30 años,2015-10-23,1985-04-12,203,Daniela,IAPOS,NaN,NaN,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,Gorosito,NaN,NaN,NaN,34 años,2023-01-18,1989-02-26,947,Yanina,AVALIAN,AS200 NG,NaN,33
884,Ruben,NaN,NaN,NaN,39 años,2023-02-08,1983-08-11,949,Jorgelina,PREVENCION SALUD,A2,NaN,39
886,Sanclemente,NaN,NaN,NaN,39 años,2023-02-10,1984-01-17,951,Jennifer,SANCOR,NG800,NaN,39
887,Gatti,NaN,NaN,NaN,39 años,2023-02-13,1983-11-17,952,Maria Eugenia,OSDE,NaN,NaN,39
893,Gomez,NaN,NaN,NaN,27 años,2023-03-02,1996-02-27,958,Jorgelina,CENTRO ASISTENCIAL,NaN,NaN,27

In [18]:
datos_limpios = filtered_fecha_nacimiento

In [19]:
datos_limpios.groupby(['Obra Social', 'edad primera cita']).count()

                                      Apellido  Comentarios  \
Obra Social        edad primera cita
AMUR               24                        1            0
                   26                        1            0
                   27                        2            0
                   28                        2            1
                   30                        1            0
...                                        ...          ...
SWISS MEDICAL      41                        1            0
                   42                        1            1
Santario santa fe  40                        1            0
UNL                40                        1            0
iAPOS              31                        1            0

                                      Correo electronico  Direccion  Edad  \
Obra Social        edad primera cita
AMUR               24                                  1          1     1
                   26                                  0          1     1
                   27                                  1          2     2
                   28                                  2          2     2
                   30                                  1          1     1
...                                                  ...        ...   ...
SWISS MEDICAL      41                                  1          1     1
                   42                                  1          1     1
Santario santa fe  40                                  0          0     1
UNL                40                                  0          1     1
iAPOS              31                                  0          1     1

                                      Fecha de creacion del registro  \
Obra Social        edad primera cita
AMUR               24                                              1
                   26                                              1
                   27                                              2
                   28                                              2
                   30                                              1
...                                                              ...
SWISS MEDICAL      41                                              1
                   42                                              1
Santario santa fe  40                                              1
UNL                40                                              1
iAPOS              31                                              1

                                      Fecha Nacimiento  ID Paciente  Nombres  \
Obra Social        edad primera cita
AMUR               24                                1            1        1
                   26                                1            1        1
                   27                                2            2        2
                   28                                2            2        2
                   30                                1            1        1
...                                                ...          ...      ...
SWISS MEDICAL      41                                1            1        1
                   42                                1            1        1
Santario santa fe  40                                1            1        1
UNL                40                                1            1        1
iAPOS              31                                1            1        1

                                      Plan Obra Social  Telefono Fijo
Obra Social        edad primera cita
AMUR               24                                1              0
                   26                                0              0
                   27                                2              0
                   28                                2              0
                   30                                1              0
...                                                ...            ...
SWISS MEDICAL      41                                0              0
                   42                                0              0
Santario santa fe  40                                0              0
UNL                40                                0              0
iAPOS              31                                0              0

[308 rows x 11 columns]

In [25]:
datos_limpios.groupby(['Obra Social']).count()

,Apellido,Comentarios,Correo electronico,Direccion,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Nombres,Plan Obra Social,Telefono Fijo,edad primera cita
Obra Social,,,,,,,,,,,,
AMUR,34,1,23,33,34,34,34,34,34,22,2,34
ARTE DE CURAR,1,0,0,1,1,1,1,1,1,1,0,1
AVALIAN,5,0,1,2,5,5,5,5,5,3,0,5
Avalian,1,0,1,1,1,1,1,1,1,1,0,1
CAJA DE INGENIEROS,4,0,2,4,4,4,4,4,4,2,0,4
CAJA FORENSE,6,0,3,3,6,6,6,6,6,0,1,6
CENTRO ASISTENCIAL,40,1,17,29,40,40,40,40,40,6,0,40
CIENCIAS ECONOMICAS,3,0,2,1,3,3,3,3,3,0,0,3
FEDERADA SALUD,5,0,3,3,5,5,5,5,5,5,0,5
FUTBOLISTAS A. AGREMIADOS,2,0,2,2,2,2,2,2,2,0,1,2
GALENO,1,0,0,0,1,1,1,1,1,1,0,1
Galeno,1,0,0,1,1,1,1,1,1,1,0,1
IAPOS,90,1,59,62,90,90,90,90,90,0,4,90
JERARQUICOS SALUD,11,0,8,10,11,11,11,11,11,6,1,11
LUZ Y FUERZA,1,0,0,0,1,1,1,1,1,0,0,1
MEDIFE,8,0,4,8,8,8,8,8,8,4,0,8
No obra social,5,0,0,0,5,5,5,5,5,0,0,5
OMINT,1,0,0,0,1,1,1,1,1,0,0,1
OPDEA,9,0,9,8,9,9,9,9,9,5,0,9
OSDE,47,0,25,33,47,47,47,47,47,27,2,47
OSECAC,2,0,0,0,2,2,2,2,2,0,0,2
OSECAC\n,1,0,1,1,1,1,1,1,1,0,0,1
OSPAC,11,0,5,4,11,11,11,11,11,2,0,11
OSPAT,4,0,2,1,4,4,4,4,4,1,0,4
OSPECON,7,0,1,1,7,7,7,7,7,0,0,7
OSPEDYC,5,0,3,3,5,5,5,5,5,0,0,5
OSPIL,7,2,4,6,7,7,7,7,7,1,0,7
OSPIM,1,0,0,1,1,1,1,1,1,0,0,1
OSPIP,1,0,1,1,1,1,1,1,1,0,0,1
OSPRERA,9,0,2,2,9,9,9,9,9,0,0,9
OSPSA,2,0,1,1,2,2,2,2,2,0,0,2
OSSEG,3,0,2,3,3,3,3,3,3,0,0,3
OSUTGRA,1,0,1,1,1,1,1,1,1,0,0,1
OSUTHGRA,2,0,1,0,2,2,2,2,2,0,0,2
PAMI,1,0,1,0,1,1,1,1,1,0,0,1
PARTICULAR,36,0,12,16,36,36,36,36,36,0,0,36
PREVENCION SALUD,92,2,63,69,92,92,92,92,92,61,3,92
Particular,1,1,1,1,1,1,1,1,1,0,0,1
SANCOR,71,5,45,53,71,71,71,71,71,58,1,71
SUTIAGA,1,0,0,0,1,1,1,1,1,0,0,1
SWISS MEDICAL,24,2,19,22,24,24,24,24,24,8,0,24
Santario santa fe,1,0,0,0,1,1,1,1,1,0,0,1
UNL,1,0,0,1,1,1,1,1,1,0,0,1
iAPOS,1,0,0,1,1,1,1,1,1,0,0,1

In [23]:
datos_limpios

,Apellido,Comentarios,Correo electronico,Direccion,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Nombres,Obra Social,Plan Obra Social,Telefono Fijo,edad primera cita
185,Gaeta,NaN,gaetanatalia@gmail.com,Sargento Cabral 495,37 años,2015-09-17,1983-01-30,198,Natalia,OSDE,NaN,NaN,32
186,Acosta,NaN,gisela.angeles@hotmail.com,Aconcagua 618,32 años,2015-09-24,1985-05-15,199,Gisela,OSDE,NaN,NaN,30
187,Furlong,NaN,leticiafurlong@live.com.ar,Montes de Oca 445,36 años,2015-10-05,1982-02-02,201,Leticia,IAPOS,NaN,NaN,33
188,Fornero,NaN,mariafornero@gmail.com,Las Araucarias 2130,36 años,2015-10-23,1981-05-20,202,Maria,OSDE,NaN,NaN,34
189,Lelli,NaN,kacomertes@hotmail.com,Uruguat 545,30 años,2015-10-23,1985-04-12,203,Daniela,IAPOS,NaN,NaN,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,Gorosito,NaN,NaN,NaN,34 años,2023-01-18,1989-02-26,947,Yanina,AVALIAN,AS200 NG,NaN,33
884,Ruben,NaN,NaN,NaN,39 años,2023-02-08,1983-08-11,949,Jorgelina,PREVENCION SALUD,A2,NaN,39
886,Sanclemente,NaN,NaN,NaN,39 años,2023-02-10,1984-01-17,951,Jennifer,SANCOR,NG800,NaN,39
887,Gatti,NaN,NaN,NaN,39 años,2023-02-13,1983-11-17,952,Maria Eugenia,OSDE,NaN,NaN,39
893,Gomez,NaN,NaN,NaN,27 años,2023-03-02,1996-02-27,958,Jorgelina,CENTRO ASISTENCIAL,NaN,NaN,27

In [47]:
datos_limpios.replace('No obra social', 'PARTICULAR', inplace=True)
datos_limpios.groupby(['Obra Social']).count().sort_values(by='Apellido', ascending=False)

c:\Users\Rafael Ortega\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py:5244: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

,Apellido,Comentarios,Correo electronico,Direccion,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Nombres,Plan Obra Social,Telefono Fijo,edad primera cita
Obra Social,,,,,,,,,,,,
PREVENCION SALUD,92,2,63,69,92,92,92,92,92,61,3,92
IAPOS,91,1,59,63,91,91,91,91,91,0,4,91
SANCOR,71,5,45,53,71,71,71,71,71,58,1,71
OSDE,47,0,25,33,47,47,47,47,47,27,2,47
PARTICULAR,42,1,13,17,42,42,42,42,42,0,0,42
CENTRO ASISTENCIAL,40,1,17,29,40,40,40,40,40,6,0,40
AMUR,34,1,23,33,34,34,34,34,34,22,2,34
SWISS MEDICAL,24,2,19,22,24,24,24,24,24,8,0,24
JERARQUICOS SALUD,11,0,8,10,11,11,11,11,11,6,1,11
OSPAC,11,0,5,4,11,11,11,11,11,2,0,11
OSPRERA,9,0,2,2,9,9,9,9,9,0,0,9
OPDEA,9,0,9,8,9,9,9,9,9,5,0,9
MEDIFE,8,0,4,8,8,8,8,8,8,4,0,8
OSPECON,7,0,1,1,7,7,7,7,7,0,0,7
OSPIL,7,2,4,6,7,7,7,7,7,1,0,7
CAJA FORENSE,6,0,3,3,6,6,6,6,6,0,1,6
AVALIAN,6,0,2,3,6,6,6,6,6,4,0,6
FEDERADA SALUD,5,0,3,3,5,5,5,5,5,5,0,5
OSPEDYC,5,0,3,3,5,5,5,5,5,0,0,5
OSPAT,4,0,2,1,4,4,4,4,4,1,0,4
CAJA DE INGENIEROS,4,0,2,4,4,4,4,4,4,2,0,4
CIENCIAS ECONOMICAS,3,0,2,1,3,3,3,3,3,0,0,3
OSSEG,3,0,2,3,3,3,3,3,3,0,0,3
OSECAC,3,0,1,1,3,3,3,3,3,0,0,3
OSUTHGRA,2,0,1,0,2,2,2,2,2,0,0,2
GALENO,2,0,0,1,2,2,2,2,2,2,0,2
OSPSA,2,0,1,1,2,2,2,2,2,0,0,2
FUTBOLISTAS A. AGREMIADOS,2,0,2,2,2,2,2,2,2,0,1,2
Santario santa fe,1,0,0,0,1,1,1,1,1,0,0,1
SUTIAGA,1,0,0,0,1,1,1,1,1,0,0,1
ARTE DE CURAR,1,0,0,1,1,1,1,1,1,1,0,1
PAMI,1,0,1,0,1,1,1,1,1,0,0,1
OSUTGRA,1,0,1,1,1,1,1,1,1,0,0,1
LUZ Y FUERZA,1,0,0,0,1,1,1,1,1,0,0,1
OSPIP,1,0,1,1,1,1,1,1,1,0,0,1
OSPIM,1,0,0,1,1,1,1,1,1,0,0,1
OMINT,1,0,0,0,1,1,1,1,1,0,0,1
UNL,1,0,0,1,1,1,1,1,1,0,0,1

In [50]:
datos_limpios.Apellido.nunique()

467

In [54]:
datos_limpios.groupby(['Apellido']).count().sort_values(by='Edad', ascending=False).head(25)

,Comentarios,Correo electronico,Direccion,Edad,Fecha de creacion del registro,Fecha Nacimiento,ID Paciente,Nombres,Obra Social,Plan Obra Social,Telefono Fijo,edad primera cita
Apellido,,,,,,,,,,,,
Romero,0,4,5,7,7,7,7,7,7,4,0,7
Gonzalez,0,4,3,5,5,5,5,5,5,2,0,5
Gomez,0,2,3,5,5,5,5,5,5,1,0,5
Barreto,0,1,3,4,4,4,4,4,4,1,0,4
Ferrero,0,3,3,4,4,4,4,4,4,1,0,4
Rinaldi,0,2,2,3,3,3,3,3,3,1,0,3
Molina,0,1,2,3,3,3,3,3,3,1,0,3
Fissore,1,3,3,3,3,3,3,3,3,1,0,3
Alvarez,0,1,2,3,3,3,3,3,3,1,0,3
Fernandez,0,1,0,3,3,3,3,3,3,0,0,3
Medina,0,1,1,3,3,3,3,3,3,0,0,3
Diaz,0,1,3,3,3,3,3,3,3,1,0,3
Re,0,2,1,3,3,3,3,3,3,1,0,3
Acosta,0,3,1,3,3,3,3,3,3,0,1,3
Roldan,0,2,2,2,2,2,2,2,2,2,0,2
Gauna,1,2,2,2,2,2,2,2,2,0,0,2
Brequis,0,0,2,2,2,2,2,2,2,0,0,2
Bravo,0,1,1,2,2,2,2,2,2,0,0,2
Sterren,1,2,2,2,2,2,2,2,2,1,0,2
Bork,0,2,1,2,2,2,2,2,2,1,0,2
Mondino,0,2,1,2,2,2,2,2,2,0,0,2
Suarez,0,2,2,2,2,2,2,2,2,0,0,2
Nasetta,0,1,2,2,2,2,2,2,2,1,0,2
Rey,0,2,2,2,2,2,2,2,2,2,0,2
Bertone,0,2,2,2,2,2,2,2,2,1,0,2

In [21]:
import numpy as np

data = np.array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0])

row = int(input())

a = data.reshape(5,6)
print (a)
print()
print(a[row])

ValueError: invalid literal for int() with base 10: ''

In [ ]:
import numpy as np

y = np.arange(1,100)

print(y)
cond = (y % 3 == 0) & (y % 5 == 0)

print(y[cond])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[15 30 45 60 75 90]

In [ ]:
import numpy as np
for i in range(1,10):
    for j in range(1,10):
        print(i*j)

import numpy as np

data = np.array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0])

1
2
3
4
5
6
7
8
9
2
4
6
8
10
12
14
16
18
3
6
9
12
15
18
21
24
27
4
8
12
16
20
24
28
32
36
5
10
15
20
25
30
35
40
45
6
12
18
24
30
36
42
48
54
7
14
21
28
35
42
49
56
63
8
16
24
32
40
48
56
64
72
9
18
27
36
45
54
63
72
81

In [ ]:
import numpy as np

data = np.array([120, 98, 150, 65, 42, 100, 190, 220, 140, 110, 88, 89, 100, 120, 50, 180, 155, 42, 89, 77, 200, 190, 125, 98, 77, 40, 39, 59, 30, 67])

exc_mean = data.mean()

data[data > exc_mean].size

12

In [ ]:
import pandas as pd

# Creamos un DataFrame con una columna de fechas de nacimiento y otra columna de fechas de interés
df = pd.DataFrame({'fecha_nacimiento': ['1990-01-01', '1995-05-12', '2000-11-23'],
                   'fecha_interes': ['2022-03-01', '2022-03-02', '2022-03-03']})

# Convertimos ambas columnas a objetos datetime64[ns]
df['fecha_nacimiento'] = pd.to_datetime(df['fecha_nacimiento'])
df['fecha_interes'] = pd.to_datetime(df['fecha_interes'])

# Calculamos la edad en años
df['edad'] = ((df['fecha_interes'] - df['fecha_nacimiento']).dt.days / 365.25).astype(int)

# Imprimimos el resultado
print(df)

In [ ]:
import pandas as pd

# Creamos un DataFrame con una columna de fechas de nacimiento y otra columna de fechas de interés
df = pd.DataFrame({'fecha_nacimiento': ['1990-01-01', '1995-05-12', '2000-11-23'],
                   'fecha_interes': ['2022-03-01', '2022-03-02', '2022-03-03']})

# Convertimos ambas columnas a objetos datetime64[ns]
df['fecha_nacimiento'] = pd.to_datetime(df['fecha_nacimiento'])
df['fecha_interes'] = pd.to_datetime(df['fecha_interes'])

# Calculamos la edad en años
df['edad'] = ((df['fecha_interes'] - df['fecha_nacimiento']).dt.days / 365.25).astype(int)

# Imprimimos el resultado
df

  fecha_nacimiento fecha_interes  edad
0       1990-01-01    2022-03-01    32
1       1995-05-12    2022-03-02    26
2       2000-11-23    2022-03-03    21

In [ ]:
import pandas as pd
from datetime import datetime

# Supongamos que tienes un DataFrame llamado 'consultas' con los datos de las pacientes

# Calcular la edad de la paciente en el momento de su primera cita
consultas['edad'] = (consultas['primera_cita'] - consultas['fecha_nacimiento']).apply(lambda x: int(x.days/365))

# Agrupar los datos por tipo de cita solicitado y calcular la edad promedio para cada grupo
promedio_edad = consultas.groupby('tipo_cita')['edad'].mean()

# Imprimir los resultados
print(promedio_edad)